root: true
env:
  es6: true
  node: true
extends:
  - 'plugin:prettier/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  createInstance: readonly
parser: '@typescript-eslint/parser'
plugins:
  - prettier
  - progress
ignorePatterns: '**/*'
rules:
  progress/activate: 1
  prettier/prettier:
    - error
    - printWidth: 120
      useTabs: false
      semi: true
      singleQuote: true
      quoteProps: consistent
      trailingComma: es5
      bracketSpacing: true
      arrowParens: always
      endOfLine: auto
      tabWidth: 2
overrides:
  - files:
      - '*.js'
      - '*.ts'
    plugins:
      - '@typescript-eslint'
      - typescript-sort-keys
      - jsdoc
      - import
      - '@nrwl/nx'
    extends:
      - 'eslint:recommended'
      - google
      - 'plugin:@typescript-eslint/eslint-recommended'
      - 'plugin:@typescript-eslint/recommended'
      - 'plugin:import/errors'
      - 'plugin:import/warnings'
      - 'plugin:import/typescript'
      - 'plugin:jsdoc/recommended'
    settings:
      import/extensions:
        - .js
        - .ts
      import/parsers:
        '@typescript-eslint/parser':
          - .ts
      import/cache:
        lifetime: Infinity
    rules:
      '@nrwl/nx/enforce-module-boundaries':
        - error
        - enforceBuildableLibDependency: true
          depConstraints:
            - sourceTag: '*'
              onlyDependOnLibsWithTags:
                - '*'
      '@typescript-eslint/no-inferrable-types': off
      no-restricted-imports:
        - error
        - patterns:
            - '.*' # Ban relative imports
      '@typescript-eslint/member-ordering':
        - error
        - default:
            - signature
            - public-static-field
            - protected-static-field
            - private-static-field
            - public-static-method
            - protected-static-method
            - private-static-method
            - public-abstract-field
            - protected-abstract-field
            - private-abstract-field
            - public-instance-field
            - protected-instance-field
            - private-instance-field
            - public-constructor
            - protected-constructor
            - private-constructor
            - public-instance-method
            - protected-instance-method
            - private-instance-method
            - public-abstract-method
            - protected-abstract-method
            - private-abstract-method
      typescript-sort-keys/interface:
        - error
        - asc
        - caseSensitive: true
          natural: true
      typescript-sort-keys/string-enum:
        - error
        - asc
        - caseSensitive: true
          natural: true
      quotes: off
      no-else-return:
        - error
        - allowElseIf: true
      sort-keys:
        - error
        - asc
        - caseSensitive: true
          natural: true
          minKeys: 2
      '@typescript-eslint/quotes':
        - error
        - backtick
      '@typescript-eslint/no-var-requires': off
      '@typescript-eslint/explicit-function-return-type': off
      '@typescript-eslint/no-unused-vars':
        - error
        - argsIgnorePattern: ^_
      import/no-namespace: off
      import/first: error
      import/exports-last: error
      import/no-duplicates: error
      import/no-commonjs: error
      import/no-dynamic-require: error
      import/order:
        - error
        - groups:
            - index
            - sibling
            - parent
            - internal
            - external
            - builtin
            - object
          newlines-between: never
          alphabetize:
            order: asc
            caseInsensitive: false
      indent: off
      no-duplicate-imports: error
      sort-imports: off
      new-cap: off
      '@typescript-eslint/no-explicit-any':
        - error
        - fixToUnknown: false
          ignoreRestArgs: false
      object-curly-spacing:
        - error
        - always
      linebreak-style: off
      computed-property-spacing:
        - error
        - never
      array-bracket-spacing: off
      prefer-rest-params: off
      require-jsdoc: off
      max-len: off
      comma-dangle: off
      object-shorthand:
        - error
        - always
        - avoidExplicitReturnArrows: true
      arrow-body-style:
        - error
        - as-needed
        - requireReturnForObjectLiteral: true
      no-dupe-else-if: error
      no-unmodified-loop-condition: error
      no-eval: error
      no-extra-label: error
      no-await-in-loop: error
      prefer-destructuring:
        - error
        - VariableDeclarator:
            array: true
            object: true
          AssignmentExpression:
            array: true
            object: true
        - enforceForRenamedProperties: false
      '@typescript-eslint/unbound-method': off
      '@typescript-eslint/no-unsafe-call': off
      '@typescript-eslint/no-unsafe-member-access': off
      '@typescript-eslint/no-unsafe-return': off
      '@typescript-eslint/no-unsafe-assignment': off
      '@typescript-eslint/prefer-enum-initializers': error
      '@typescript-eslint/prefer-literal-enum-member': off
      '@typescript-eslint/unified-signatures': error
      '@typescript-eslint/ban-ts-comment': error
      no-undef-init: error
      no-magic-numbers:
        - error
        - enforceConst: true
          detectObjects: false
          ignore:
            - 0
            - 1
      import/no-unresolved: error
      prefer-template: error
      no-useless-concat: error
      no-constant-condition:
        - error
        - checkLoops: true
      prefer-promise-reject-errors:
        - error
        - allowEmptyReject: false
      no-case-declarations: error
      no-irregular-whitespace:
        - error
        - skipStrings: false
          skipComments: false
          skipRegExps: false
          skipTemplates: false
      '@typescript-eslint/adjacent-overload-signatures': error
      no-invalid-this: off
      '@typescript-eslint/no-invalid-this': error
      prefer-const:
        - error
        - destructuring: any
          ignoreReadBeforeAssign: false
      camelcase: off
      valid-jsdoc: off
      'jsdoc/require-jsdoc': warn # @todo change it to error but we should fix all current jsdoc errors
      curly:
        - error
        - all
      '@typescript-eslint/triple-slash-reference':
        - error
        - path: never
          types: never
          lib: never
      '@typescript-eslint/no-empty-interface':
        - error
        - allowSingleExtends: false
      '@typescript-eslint/restrict-template-expressions': off
      '@typescript-eslint/ban-types': error
      no-undef:
        - error
        - typeof: true
      no-useless-escape: error
      no-prototype-builtins: error
      require-await: off
      no-empty-function: off
      no-var: error
      spaced-comment:
        - error
        - always
        - markers:
            - /
      '@typescript-eslint/no-empty-function':
        - error
        - allow:
            - decoratedFunctions
      padding-line-between-statements:
        - error
        - blankLine: always
          prev:
            - '*'
          next:
            - class
            - do
            - for
            - if
            - return
            - switch
            - try
        - blankLine: always
          prev:
            - block-like
            - const
            - let
            - var
          next: '*'
        - blankLine: never
          prev:
            - const
            - let
            - var
          next:
            - const
            - let
            - var
      '@typescript-eslint/explicit-member-accessibility': error
  - files:
      - '*.js'
    extends:
      - 'plugin:@nrwl/nx/javascript'
    rules:
      '@typescript-eslint/explicit-module-boundary-types': off
      import/no-commonjs: off
  - files:
      - '*.ts'
    extends:
      - 'plugin:@nrwl/nx/typescript'
    rules:
      '@typescript-eslint/explicit-function-return-type':
        - error
        - allowExpressions: false
          allowTypedFunctionExpressions: false
          allowHigherOrderFunctions: false
      '@typescript-eslint/no-var-requires': error
