extends:
  - '../../.eslintrc.yml'
ignorePatterns:
  - '!**/*'
overrides:
  - files:
      - '*.ts'
    extends:
      - plugin:@nrwl/nx/angular
      - plugin:@angular-eslint/template/process-inline-templates
      - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
    parserOptions:
      project:
        - apps/website/tsconfig.*?.json
    settings:
      import/resolver:
        typescript:
          alwaysTryTypes: true
          project:
            - apps/website/tsconfig.*?.json
    rules:
      '@angular-eslint/directive-selector':
        - error
        - type: attribute
          prefix: rpgCharacter
          style: camelCase
      '@angular-eslint/component-selector':
        - error
        - type: element
          prefix: rpg-character
          style: kebab-case
      '@typescript-eslint/require-await': error
      '@typescript-eslint/restrict-plus-operands':
        - error
        - checkCompoundAssignments: true
      '@typescript-eslint/prefer-regexp-exec': error
      '@typescript-eslint/prefer-readonly-parameter-types': # @todo change it to error once the nested object issue is resolved (https://github.com/typescript-eslint/typescript-eslint/issues/2823)
        - warn
        - ignoreInferredTypes: true
          checkParameterProperties: false
      '@typescript-eslint/prefer-readonly': error
      '@typescript-eslint/await-thenable': error
      '@typescript-eslint/no-misused-promises':
        - error
        - checksConditionals: true
          checksVoidReturn: true
      '@typescript-eslint/no-floating-promises':
        - error
        - ignoreVoid: true
      '@typescript-eslint/naming-convention':
        - error
        - selector: default
          format:
            - camelCase
        - selector: variable
          format:
            - camelCase
            - UPPER_CASE
        - selector: variable
          types:
            - boolean
          format:
            - PascalCase
            - UPPER_CASE
          prefix:
            - is
            - has
            - should
            - contains
            - as
            - to
        - selector: parameter
          format:
            - camelCase
          leadingUnderscore: allow
        - selector: parameter
          types:
            - boolean
          format:
            - PascalCase
          leadingUnderscore: allow
          prefix:
            - is
            - has
            - should
            - contains
            - as
            - to
        - selector: function
          format:
            - camelCase
        - selector: memberLike
          modifiers:
            - private
          format:
            - camelCase
          leadingUnderscore: require
        - selector: memberLike
          modifiers:
            - protected
          format:
            - camelCase
          leadingUnderscore: require
        - selector: typeLike
          format:
            - PascalCase
        - selector: typeParameter
          format:
            - PascalCase
          prefix:
            - T
        - selector: interface
          format:
            - PascalCase
          prefix:
            - I
        - selector: typeAlias
          format:
            - PascalCase
          prefix:
            - I
        - selector: enumMember
          format:
            - UPPER_CASE
        - selector: enum
          format:
            - PascalCase
          prefix:
            - E
  - files:
      - '*.html'
    extends:
      - plugin:@nrwl/nx/angular-template
